add publish step

diff --git a/.github/workflows/publish-mod.yml b/.github/workflows/publish-mod.yml
--- a/.github/workflows/publish-mod.yml
+++ b/.github/workflows/publish-mod.yml
@@ -396,5 +396,20 @@ jobs:
           }
      
       - name: Publish mod
-        shell: pwsh
+        if: ${{ !inputs.dry_run }}
+        shell: bash
+        env:
+          STEAMCMD_PATH: ${{ steps.steamcmd.outupts.executable }}
+          STEAM_USER: ${{ secrets.STEAM_USER }}
         run: |
+          # run the steam publish script
+          ./Tools/SteamPublish.sh "$MOD_NAME"
+
+          if [[ -z "FILE_ID" ]]; then
+            echo "ERROR: SteamCMD did not return a published file ID."
+            rm "$TMP_VDF"
+            exit 1
+          fi
+
+          echo "Published file id: $FILE_ID"
+          echo "Successfully published $MOD_NAME $MOD_VERSION to the Steam Workshop."
